export const QUERY_KEYS = {
  siteSettings: 'site-settings',
  hero: 'hero',
  courses: 'courses',
  craftItems: 'craft-items',
  companies: 'companies',
  emexPoints: 'emex-points',
  emexIntro: 'emex-intro',
  emexSellerHubPoints: 'emex-seller-hub-points',
  emexSellerHubIntro: 'emex-seller-hub-intro',
  sberbankMetalPoints: 'sberbank-metal-points',
  sberbankDepositPoints: 'sberbank-deposit-points',
  sberbankMetalIntro: 'sberbank-metal-intro',
  sberbankDepositIntro: 'sberbank-deposit-intro',
  cloudpaymentWebsiteIntro: 'cloudpayment-website-intro',
  cloudpaymentWebsitePoints: 'cloudpayment-website-points',
  about: 'about',
  drawer: 'drawer',
};
